#!/usr/bin/env python
import logging
import optparse
import asyncore

from state_server.core import server

def main():
    parser = optparse.OptionParser()
    parser.add_option('-d', '--debug', action='store_true',
        help='Turn on debugging messages')
    parser.add_option('-p', '--port', metavar='PORT',
        help='Port number', default='12300')

    (opts, args) = parser.parse_args()

    lvl = logging.INFO
    if opts.debug:
        lvl = logging.DEBUG

    logging.basicConfig(level=lvl)

    logging.debug('Init')
    host, port = 'localhost', int(opts.port)
    srv = server.StateServer(host, port)
    logging.info('Listening on %s %s' % (host, port))

    asyncore.loop()

if __name__ == "__main__":
    main()
