#!/usr/bin/env python

import sys
import optparse

def main():
    parser = optparse.OptionParser()
    parser.add_option('-r', '--rel', action='store_true',
        help='Output relative timestamps')

    (opts, args) = parser.parse_args()

    if len(args) != 2:
        print >> sys.stderr, 'Usage: state_extract variable_name FILE'
        sys.exit(1)

    var = args[0]
    fpath = args[1]

    try:
        file = open(fpath, 'r')
    except IOError:
        print >> sys.stderr, 'Can\'t open file "%s" for reading' % fpath
        sys.exit(1)

    n1time = None

    for line in file.readlines():
        time, event = line.split()
        time = float(time)

        if n1time is None:
            n1time = time

        if opts.rel:
            time -= n1time

        typ, data = event.split(':')
        if typ=='SET':
            varname, value = data.split('=')
            if varname == var:
                print '%.2f %s' % (time, value)
    file.close()

if __name__ == "__main__":
    main()
